include:
  - local: /common/gitlab/quality.yml

variables:
  STACK_DIR: nextjs

secret-scan:
  extends: .secret-scan-template

dependency-audit:
  extends: .dependency-audit-template

quality:
  extends: .quality-template

commitlint:
  extends: .commitlint-template

test:
  extends: .test-template

build:
  extends: .build-template
